// <auto-generated />
using Destinations.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Destinations.Migrations
{
    [DbContext(typeof(DestinationsContext))]
    [Migration("20200128192627_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Destinations.Models.Destination", b =>
                {
                    b.Property<int>("DestinationId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City");

                    b.Property<string>("Country");

                    b.HasKey("DestinationId");

                    b.ToTable("Destinations");

                    b.HasData(
                        new
                        {
                            DestinationId = 1,
                            City = "Prague",
                            Country = "Czech Republic"
                        },
                        new
                        {
                            DestinationId = 2,
                            City = "Berlin",
                            Country = "Germany"
                        },
                        new
                        {
                            DestinationId = 3,
                            City = "Talinn",
                            Country = "Estonia"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
