// <auto-generated />
using System;
using Destinations.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Destinations.Migrations
{
    [DbContext(typeof(DestinationsContext))]
    [Migration("20200129162055_Update")]
    partial class Update
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Destinations.Models.Destination", b =>
                {
                    b.Property<int>("DestinationId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City");

                    b.Property<string>("Country");

                    b.Property<int>("Rating");

                    b.HasKey("DestinationId");

                    b.ToTable("Destinations");

                    b.HasData(
                        new
                        {
                            DestinationId = 1,
                            City = "Prague",
                            Country = "Czech Republic",
                            Rating = 10
                        },
                        new
                        {
                            DestinationId = 2,
                            City = "Berlin",
                            Country = "Germany",
                            Rating = 10
                        },
                        new
                        {
                            DestinationId = 3,
                            City = "Talinn",
                            Country = "Estonia",
                            Rating = 9
                        });
                });

            modelBuilder.Entity("Destinations.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<int?>("DestinationId");

                    b.Property<string>("Text");

                    b.HasKey("ReviewId");

                    b.HasIndex("DestinationId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Destinations.Models.Review", b =>
                {
                    b.HasOne("Destinations.Models.Destination", "Destination")
                        .WithMany("Reviews")
                        .HasForeignKey("DestinationId");
                });
#pragma warning restore 612, 618
        }
    }
}
